#!/bin/env bash

# shellcheck disable=SC2155
dir=$(dirname "$(readlink -f "$0")")

# 定义 curses_run 函数
curses_run() {
    local executable=$1
    local executable_path="$dir/bin/$executable"

    if [[ -x $executable_path ]]; then
        echo "Running $executable..."
        "$executable_path" "$@"
    else
        echo "Executable $executable not found."
    fi
}

# 定义 run_curses 的 zsh 完成脚本
_curses_run_complete() {
    local executables=()
    for f in "$dir"/bin/*; do
        if [[ -x $f ]]; then
            executables+=("$(basename "$f")")
        fi
    done
    # shellcheck disable=SC2128
    _arguments "1:executable:($executables)"
}

# 注册 curses_run 的 zsh 完成脚本
compdef _curses_run_complete curses_run

# 使用时执行 curses_run 函数
# curses_run helloWorld
